//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadParcial2Relm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Parcial2RelmEntities1 : DbContext
    {
        public Parcial2RelmEntities1()
            : base("name=Parcial2RelmEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Canal> Canal { get; set; }
        public virtual DbSet<Programa> Programa { get; set; }
    
        public virtual int paCanalActualizar(Nullable<int> id, string nombre, string frecuencia)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var frecuenciaParameter = frecuencia != null ?
                new ObjectParameter("frecuencia", frecuencia) :
                new ObjectParameter("frecuencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paCanalActualizar", idParameter, nombreParameter, frecuenciaParameter);
        }
    
        public virtual int paCanalEliminarLogico(Nullable<int> idCanal)
        {
            var idCanalParameter = idCanal.HasValue ?
                new ObjectParameter("idCanal", idCanal) :
                new ObjectParameter("idCanal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paCanalEliminarLogico", idCanalParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> paCanalInsertar(string nombre, string frecuencia)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var frecuenciaParameter = frecuencia != null ?
                new ObjectParameter("frecuencia", frecuencia) :
                new ObjectParameter("frecuencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("paCanalInsertar", nombreParameter, frecuenciaParameter);
        }
    
        public virtual ObjectResult<paCanalListar_Result> paCanalListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paCanalListar_Result>("paCanalListar", parametroParameter);
        }
    
        public virtual int paProgramaActualizar(Nullable<int> id, Nullable<int> idCanal, string titulo, string descripcion, Nullable<int> duracion, string productor, Nullable<System.DateTime> fechaEstreno)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idCanalParameter = idCanal.HasValue ?
                new ObjectParameter("idCanal", idCanal) :
                new ObjectParameter("idCanal", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("duracion", duracion) :
                new ObjectParameter("duracion", typeof(int));
    
            var productorParameter = productor != null ?
                new ObjectParameter("productor", productor) :
                new ObjectParameter("productor", typeof(string));
    
            var fechaEstrenoParameter = fechaEstreno.HasValue ?
                new ObjectParameter("fechaEstreno", fechaEstreno) :
                new ObjectParameter("fechaEstreno", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paProgramaActualizar", idParameter, idCanalParameter, tituloParameter, descripcionParameter, duracionParameter, productorParameter, fechaEstrenoParameter);
        }
    
        public virtual int paProgramaEliminarLogico(Nullable<int> idPrograma)
        {
            var idProgramaParameter = idPrograma.HasValue ?
                new ObjectParameter("idPrograma", idPrograma) :
                new ObjectParameter("idPrograma", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paProgramaEliminarLogico", idProgramaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> paProgramaInsertar(Nullable<int> idCanal, string titulo, string descripcion, Nullable<int> duracion, string productor, Nullable<System.DateTime> fechaEstreno)
        {
            var idCanalParameter = idCanal.HasValue ?
                new ObjectParameter("idCanal", idCanal) :
                new ObjectParameter("idCanal", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("duracion", duracion) :
                new ObjectParameter("duracion", typeof(int));
    
            var productorParameter = productor != null ?
                new ObjectParameter("productor", productor) :
                new ObjectParameter("productor", typeof(string));
    
            var fechaEstrenoParameter = fechaEstreno.HasValue ?
                new ObjectParameter("fechaEstreno", fechaEstreno) :
                new ObjectParameter("fechaEstreno", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("paProgramaInsertar", idCanalParameter, tituloParameter, descripcionParameter, duracionParameter, productorParameter, fechaEstrenoParameter);
        }
    
        public virtual ObjectResult<paProgramaListar_Result> paProgramaListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paProgramaListar_Result>("paProgramaListar", parametroParameter);
        }
    }
}
